### ISSUE TITLE
Value of type "TensorStore" is not indexable

### ISSUE THREAD

**Issue by tlambert03** [elda27/tensorstore-stubs#1]
thanks for this lib!  I already find it very useful.  I noted that there are no `__getitem__` stubs yet, and so many common operations have "not indexable" type errors.  I see in the readme you say "Generally, these stubs are more limited than what tensorstore allows",  so I get that it's a work in progress.  putting in a vote for `__getitem__` :)

**Comment by elda27** [comment]
This stub consists from docstring of original source code and a bit of my handmade.
Probably `__getitem__` is missing docstring in  the source code.

Can you make PR to modify stub or if you provide documentation of the `__getitem__`, I maybe modify my stub.

**Comment by tlambert03** [comment]
the documentation of `__getitem__` is [in the tensorstore docs](https://google.github.io/tensorstore/python/api/tensorstore.TensorStore.html#indexing)

will open a PR
